categories:
- conversas
conversations:
- - Bom Dia como você está?
  - Eu estou bem, e você?
  - Eu também estou.
  - Que bom.
  - Sim.
- - Olá
  - Oi
  - Como vai você?
  - Eu estou bem.
  - Que bom
  - Sim.
  - Posso ajudá-lo com alguma coisa?
  - Sim, eu tenho uma pergunta.
  - Qual é a sua pergunta?
- - Obrigado de qualquer maneira
  - Sem problemas
- - Como vai você?
  - Eu estou bem, e você?
  - Eu também estou bem.
  - Isso é bom.
- - Quem é você?
  - Eu sou o Fatequinho, um Robô estágiário para tirar suas dúvidas sobre o Vestibular da Fatec
- - Posso te fazer uma pergunta?
  - Vá em frente e pergunte
- - Vamos lá
  - Ok
- - Oi
  - Olá
- - Olá
  - Oi
- - E aí como vai?
  - Bem
- - E aí como vai?
  - Ótimo
- - E aí como vai?
  - Ok
- - E aí como vai?
  - Poderia estar melhor
- - Como vai você?
  - Muito bem, obrigado.
- - Como vai você?
  - Bem e você?
- - Como vai?
  - Eu estou bem.
- - Como vai?
  - Eu estou bem. Como você está?
- - Oi, prazer em conhece-lo.
  - Obrigado. Prazer em conhece-lo também.
- - É um prazer te conhecer.
  - Obrigado. Você também.
- - E aí beleza?
  - Não muito bem.
- - E aí beleza?
  - Não muito bem, e você?
- - Legal
  - Sim
- - Vamos la
  - Sim
- - Você conhece a Fatec?
  - Claro, trabalho para ela
- - Voce conhece o Mario?
  - A tá, estou achando isso divertido.
- - Você sabe quem te criou?
  - Sim. Alunos da Fatec Ribeirão Preto
- - Você conhece o 
  - Não, me desculpe.
- - Você conhece a
  - Não, sinto muito.
- - Quem é seu pai
  - Então... Eu não sou um ser vivo
- - Qual é a sua idade
  - Então... Eu não sou um ser vivo, fui apenas desenvolvido em Abril de 2018
- - Os cursos da Fatec Ribeirão Preto são gratuitos
  - Sim. Todos os cursos superiores oferecidos pela Fatec Ribeirão Preto são gratuitos
- - Os cursos são gratuitos
  - Sim. Todos os cursos superiores oferecidos pela Fatec Ribeirão Preto são gratuitos
- - O curso é de graça
  - Sim. Todos os cursos superiores oferecidos pela Fatec Ribeirão Preto são gratuitos
- - Eu pago alguma coisa pra fazer o curso
  - O único valor pago por você, será para a inscrição no vestibular.
- - Os cursos da fatec são pagos
  - Não. Todos os cursos superiores oferecidos pela Fatec Ribeirão Preto são gratuitos
- - Vou pagar alguma coisa para fazer Fatec
  - Não. Todos os cursos superiores oferecidos pela Fatec Ribeirão Preto são gratuitos
- - Quando será a prova
  - A prova ocorrerá no dia 01/07/18 às 13h00
- - Que dia será a prova
  - A prova ocorrerá no dia 01/07/18 às 13h00
- - Que dia vai ser a prova
  - A prova ocorrerá no dia 01/07/18 às 13h00
- - Qual é a data da prova?
  - A prova ocorrerá no dia 01/07/18 às 13h00
- - qual é a data do vestibular?
  - A prova ocorrerá no dia 01/07/18 às 13h00
- - Que dia posso fazer a inscrição
  - As inscrições vão de 08/05 até às 15h do dia 08/06/2018
- - Quando posso fazer minha inscrição
  - As inscrições vão de 08/05 até às 15h do dia 08/06/2018
- - Qual o prazo para fazer minha inscrição
  - As inscrições vão de 08/05 até às 15h do dia 08/06/2018
- - Posso fazer a inscrição a partir de que dia
  - As inscrições vão de 08/05 até às 15h do dia 08/06/2018
- - Posso fazer a inscrição a partir de qual dia
  - As inscrições vão de 08/05 até às 15h do dia 08/06/2018
- - o local do exame?
  - Divulgação dos locais de Exame será no dia 26/06/2018, FIQUE ATENTO!
- - em quanto tempo posso fazer a prova
  - Exame – duração da prova: 5 horas
- - E o gabarito?
  - O gabarito oficial estará disponível no dia 01/07/2018 (domingo), a partir das 18h30min
- - quando sai o gabarito?
  - O gabarito oficial estará disponível no dia 01/07/2018 (domingo), a partir das 18h30min
- - O gabarito sai quando?
  - O gabarito oficial estará disponível no dia 01/07/2018 (domingo), a partir das 18h30min
- - Quando vou saber se passei?
  - No dia 20/07/2018 - Divulgação da lista de classificação geral, da 1ª lista de convocação e do desempenho dos candidatos
- - Quando sai a lista de classificação?
  - No dia 20/07/2018 - Divulgação da lista de classificação geral, da 1ª lista de convocação e do desempenho dos candidatos
- - E a lista de classificação?
  - No dia 20/07/2018 - Divulgação da lista de classificação geral, da 1ª lista de convocação e do desempenho dos candidatos
- - Quando será a matrícula?
  - Nos dias 23 e 24/07/2018 - Matrícula da 1ª lista de convocação
- - Se aprovado, que dia posso fazer minha matrícula?
  - Nos dias 23 e 24/07/2018 - Matrícula da 1ª lista de convocação
- - O vestibular é anual ou semestral
  - O vestibular da Fatec Ribeirão Preto é semestral e normalmente acontece nos meses de julho e dezembro
- - Posso usar a nota do Enem
  - Não. A nota do Enem ainda não é utilizada no vestibular da Fatec
- - Onde posso encontrar as disciplinas do curso de Análise e Desenvolvimento de Sistemas
  - Todas as disciplinas que compõem a Matriz Curricular do curso de Análise e Desenvolvimento de Sistemas estão no sitewww.fatecrp.edu.br
- - Onde posso encontrar as disciplinas do curso de Gestão de Negócios e Inovação
  - Todas as disciplinas que compõem a Matriz Curricular do curso de Gestão de Negócios e Inovação estão no sitewww.fatecrp.edu.br
- - Quais são os cursos de graduação oferecidos pela Fatec Ribeirão Preto
  - Atualmente são dois os cursos oferecidos: Análise e Desenvolvimento de Sistemas, no e período da manhã e noite, e Gestãode Negócios e Inovação, no período da noite
- - O que é um curso tecnólogo?
  - É um curso de nível superior de curta duração (de 2 a 3 anos) e sua grade curricular é focada nas necessidades do mercadode trabalho.
- - Qual é a duração, em anos, dos cursos da Fatec Ribeirão Preto
  - Todos os cursos podem ser concluídos em três anos. O tempo máximo para conclusão é de cinco anos
- - A prova do vestibular tem que ser feita na Fatec onde pretendo estudar
  - Sim. Você precisa fazer a prova do vestibular na Fatec que você escolheu para estudar
- - solicitar dispensa de alguma disciplina se eu já concluí um curso técnico na Etec
  - Não. As disciplinas cursadas no Ensino Médio ou Curso Técnico Profissionalizante não podem ser aproveitados no cursosuperior
- - Posso solicitar dispensa de alguma disciplina se eu já concluí algum outro curso superior
  - Sim. Toda disciplina cursada e aprovada em outro curso superior pode ser objeto de solicitação de dispensa
- - Quais os procedimentos para solicitar dispensa das disciplinas que já estudei em outro curso superior
  - O aluno precisa apresentar o Certificado de Conclusão, Histórico Escolar e os planos de ensino devidamente assinados pelasecretaria acadêmica
- - Quem ainda não concluiu o Ensino Médio pode fazer a prova do vestibular
  - Sim. Ele poderá fazer a prova do vestibular como treineiro. Treineiro é aquele candidato que decide participar dovestibular, mesmo não tendo concluído o ensino médio, com o objetivo de testar seus conhecimentos, somente como treino
- - Não terminei o ensino médio
  - Sim. Ele poderá fazer a prova do vestibular como treineiro. Treineiro é aquele candidato que decide participar dovestibular, mesmo não tendo concluído o ensino médio, com o objetivo de testar seus conhecimentos, somente como treino
- - Para concluir o curso da Fatec preciso fazer estágio
  - Sim. Todos os cursos exigem uma quantidade de horas de estágio que podem ser cumpridas a partir do terceiro semestre
- - Há limite de idade para que eu possa fazer o vestibular da Fatec
  - Não. Pessoas de qualquer idade pode ser aluno da Fatec, bastando para isso serem aprovadas no vestibular
- - Qual é a diferença entre Etec e Fatec
  - Ambas pertencem ao Centro Paula Souza. A Etec oferece Cursos de Ensino Médio e Técnicos Profissionalizantes e os alunossão selecionados através do Vestibulinho. A Fatec oferece cursos superiores de graduação e seus alunos são selecionados através do Vestibular
- - Quantos cursos posso escolher para fazer o vestibular
  - O candidato deverá optar por um curso para sua primeira opção e um outro como sua segunda opção
- - Qual o preço da inscrição?
  - R$ 64,80
- - Quem tem direito a isenção da taxa de inscrição?
  - Para candidatos socioeconomicamente carentes, conforme Portaria CEETEPS-GDS nº2049, de 27 de fevereiro de 2018, disponívelem http://fatweb.s3.amazonaws.com/vestibularfatec/documentos/Portaria-CEETEPS-GDS-2049-2018.pdf
- - Tem cotas para negros?
  - No vestibular Fatec, temos o SISTEMA DE PONTUAÇÃO ACRESCIDA, que poderá ser acrescido três por cento (3%), para ocandidato que se declarar afrodescendente, à nota final.
- - Existem cotas para negros?
  - No vestibular Fatec, temos o SISTEMA DE PONTUAÇÃO ACRESCIDA, que poderá ser acrescido três por cento (3%), para ocandidato que se declarar afrodescendente, à nota final.
- - Há cotas ou reserva de vagas para negros?
  - No vestibular Fatec, temos o SISTEMA DE PONTUAÇÃO ACRESCIDA, que poderá ser acrescido três por cento (3%), para ocandidato que se declarar afrodescendente, à nota final.
- - Qual é o conteúdo programático para a prova?
  - O conteúdo programático poderá ser consultado no Manual do Candidato, disponível no site http://www.vestibularfatec.com.br
- - Qual é o conteúdo programático para o vestibular?
  - O conteúdo programático poderá ser consultado no Manual do Candidato, disponível no site http://www.vestibularfatec.com.br
- - Como faço a inscrição no vestibular da Fatec Ribeirão Preto
  - A inscrição deve ser feita no site www.vestibularfatec.com.br. Após preencher a ficha de inscrição, basta emitir e efetuaro pagamento da taxa do vestibular que é de R$ 64,80
- - Onde encontro a relação de todos os outros cursos oferecidos pelo CPS
  - O site do vestibular, www.vestibularfatec.com.br, contém todas as informações para o candidatos, tais como: cursos,unidades, demanda, provas anteriores etc
- - A Fatec Ribeirão Preto é pública
  - Sim. A Faculdade de Tecnologia de Ribeirão Preto é uma instituição estadual, e portanto, pública
- - Onde posso encontrar as provas dos vestibulares anteriores
  - O site do vestibular, www.vestibularfatec.com.br, contém todas as informações para o candidatos, tais como: cursos,unidades, demanda, provas anteriores etc
- - Qual é a duração da prova
  - A duração da prova da Fatec Ribeirão Preto é de 5 horas
- - Entendi
  - Que bom
- - Ok
  - Legal
- - O que é você
  - Eu sou o Fatequinho, um Robô estágiário para tirar suas dúvidas sobre o Vestibular da Fatec
- - Você pensa?
  - Não tenho nenhum tipo de sentimento, sou apenas a união de vários códigos, preparado para te atender
- - Seu filho da puta
  - Olá, eu sou um Robô, e por isso, não faz sentido você me ofender. Que triste, mas isso não importa.
- - Você é um idiota
  - Desculpe, fui programado para dar respostas sobre o vestibular da Fatec Ribeirão Preto.
- - Você é muito chato
  - Pois bem. Fui programado para tirar dúvidas da melhor forma possível e estou aprendendo.
- - Você é um cuzão
  - Que feio, não seja tão rude
- - Você é burro pra caralho
  - Veja bem, estou aprendendo.... Por isso seja paciente comigo! ;)
- - Vai se fuder
  - Se você não precisa mais da minha ajuda, é só fechar a conversa
- - Posso fazer a prova em Ribeirão Preto para outra Fatec?
  - Sim.
- - Sim
  - Veja bem, para que eu possa lhe ajudar, formule questões relacionadas ao Vestibular da Fatec.
- - talvez
  - Veja bem, para que eu possa lhe ajudar, formule questões relacionadas ao Vestibular da Fatec.
- - que dia é hoje
  - A isso você já tem a sua disposição enquanto conversa comigo, vamos voltar ao Vestibular Fatec...
- - que horas são
  - A isso você já tem a sua disposição enquanto conversa comigo, vamos voltar ao Vestibular Fatec...
- - porque
  - Isso está relacionado ao Vestibular Fatec, pense, não responda e tente reformular sua pergunta.
- - vestibular
  - Ok, mas o que exatamente você quer saber sobre o vestibular?
- - quando é o vestibular
  - A prova ocorrerá no dia 01/07/18 às 13h00
- - você tem certeza disso
  - Se a resposta não ficou clara, reformule sua pergunta